// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Donation struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Amount        int32
	UserID        uuid.UUID
	NonProfitName string
}

type NonProfit struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Address   string
	Name      string
	Email     string
	OwnerID   uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	IsOwner        bool
	NonProfitID    uuid.NullUUID
}
